### ISSUE TITLE
Create the design for pages in figma

### ISSUE THREAD

**Issue by zaqbez39me** [zaqbez39me/Timer-management-Web-App#4]
### **Some good examples:**

- [**Countdown template**](https://www.figma.com/community/file/1233502634517544198/Countdown-timer-%7C-Design-League)
-  [**Loading template**](https://www.figma.com/community/file/1230475151614227517)
- [**Timer in window**](https://www.figma.com/community/plugin/820311256083321341/Timer)
 _1. Interesting timer (buttons can be good template for our tiemer buttons)_
_2. Would be great two have each timer in window as it is in this template_

### **Some figma tools**

- [**Figma automator**](https://www.figma.com/community/plugin/1005114571859948695/Automator)

### **Tools for future frontend part**

- [**Figma to react**](https://www.figma.com/community/plugin/862039267149408972/Figma-to-React)

**Comment by AlmetovKamil** [comment]
Created first version of a design in figma:
https://www.figma.com/file/sqj1TrWbGkFjIaBBuK0mWa/SNA-project?type=design&node-id=0%3A1&t=rbjReYd5k486fqsF-1

**Comment by zaqbez39me** [comment]
1. Change the Email field on username field and remove first name and last name from login page.
2. Remove settings button from timers. Instead use the changable name field where changes would apply on enter pressed.
3. Think about some other fonts (not neccessary) and try to play with styles. For example, add shadow or something like this

**Comment by VadigullinElmir1** [comment]
I am making premature html layout of the design. The exclusion of the "auras" from the design of the buttons would greatly simplify the process

**Comment by AlmetovKamil** [comment]
Design for the front-end part is complete and available by the link: 
https://www.figma.com/file/sqj1TrWbGkFjIaBBuK0mWa/SNA-project?type=design&node-id=0%3A1&t=rbjReYd5k486fqsF-1
