### ISSUE TITLE
Write the documentation in lab format for completed backend part

### ISSUE THREAD

**Issue by zaqbez39me** [zaqbez39me/Timer-management-Web-App#7]
The main purpose of documentation here is to provide the reader the complete information about work proccess and result of System Administation part. The documentation should also include illustrative pictures and their description.

_Preferably, the documentation should be done in [Notion](https://www.notion.so/), so each team member would have an ability to update it during further development._

**Comment by Dirakon** [comment]
Here's the current read-only draft of the report: https://gist.github.com/Dirakon/aeb76cee06943a1247165250fad56af6
